### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isVisible' of undefined

### ISSUE THREAD

**Issue by kalon33** [panur/kartalla#16]
Yesterday I made kartalla working with a .json file, but today with the same one, I trigger these errors:

Uncaught TypeError: Cannot read property 'isVisible' of undefined
    at ControllerTrip.updateOnMap (controller.js:363)
    at updateTripsOnMap (controller.js:108)
    at Controller.update (controller.js:100)
    at processTick (main.js:176)
    at main.js:162
ControllerTrip.updateOnMap @ controller.js:363
updateTripsOnMap @ controller.js:108
Controller.update @ controller.js:100
processTick @ main.js:176
(anonymous) @ main.js:162
controller.js:363 

What's the problem?

**Comment by panur** [comment]
Without seeing the json file it's difficult to say what's the problem. I'm guessing you generated the json file by yourself. Were there any errors when you generated the file? Do you have the same problem also with the pregenerated json files (https://14142.net/kartalla/json/)?

**Comment by kalon33** [comment]
No I didn't get any error using HSL. I used this dataset, that lead to this JSON file (renamed in .txt to be able to upload it)
[SEM-GTFS.zip](https://github.com/panur/kartalla/files/788254/SEM-GTFS.zip)
[tag.txt](https://github.com/panur/kartalla/files/788258/tag.txt)

I also get that error:

```
TypeError: state.tripTypeInfo is undefined[En savoir plus] controller.js:363:1
	ControllerTrip/this.updateOnMap http://localhost/kartalla/js/controller.js:363:1
	updateTripsOnMap http://localhost/kartalla/js/controller.js:108:29
	Controller/this.update http://localhost/kartalla/js/controller.js:100:9
	processTick http://localhost/kartalla/js/main.js:176:13
	Timing/this.init/state.intervalId< http://localhost/kartalla/js/main.js:162:60
```

With another dataset that lead to that JSON file, I got the following error:
[stif.txt](https://github.com/panur/kartalla/files/788282/stif.txt)


```
TypeError: encoded is undefined[En savoir plus] map_leaflet.js:115:13
	decodeLine http://localhost/kartalla/js/map_leaflet.js:115:13
	MapApiMap/this.decodePath http://localhost/kartalla/js/map_leaflet.js:109:16
	Map/this.decodePath http://localhost/kartalla/js/map.js:121:16
	initMarker http://localhost/kartalla/js/controller.js:280:24
	ControllerTrip/this.updateOnMap http://localhost/kartalla/js/controller.js:365:25
	updateTripsOnMap http://localhost/kartalla/js/controller.js:108:29
	Controller/this.update http://localhost/kartalla/js/controller.js:100:9
	processTick http://localhost/kartalla/js/main.js:176:13
	Timing/this.init/state.intervalId<
```

**Comment by panur** [comment]
Thanks for the files. The first problem is that route type 715 is missing here:

https://github.com/panur/kartalla/blob/master/gtfs2json/gtfs2json_gtfs.py#L73

After adding it I can see some buses and trams in Grenoble:

https://14142.net/kartalla/?_file=tmp/tag&lat=45.130711&lng=5.7431030&zoom=11&types=bus_tram

I'm afraid I don't have time to investigate this any further until next week.

**Comment by kalon33** [comment]
Ok, thanks for your help. No matter if it's only next week, it's nice to have a look at it. I just committed a PR #17 to fix that, and another missing route type I found in the second dataset. I also encountered another issue with gtfs2json that I will report just after this comment.

**Comment by panur** [comment]
I had finally time to investigate this issue more closely. The remaining problem with SEM-GTFS.zip is that gtfs2json assumes that each service has one or two directions and that each direction has one shape. While this assumption is valid with HSL's GTFS data it's not with the SEM's data.

It may be possible to modify gtfs2json to support services with many shapes but it's better to create a new issue for that.
