### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by kalon33** [panur/kartalla#18]
I got some trouble using the shapes.txt file I generated using an ARCgis toolbox:

```
Traceback (most recent call last):
  File "./gtfs2json.py", line 72, in <module>
    _main()
  File "./gtfs2json.py", line 35, in _main
    routes = gtfs2json_gtfs.get_routes(args.input_dir)
  File "/home/nicolas/packaging/sources/kartalla/gtfs2json/gtfs2json_gtfs.py", line 20, in get_routes
    shapes = _parse_shapes(os.path.join(input_dir, 'shapes.txt'))
  File "/home/nicolas/packaging/sources/kartalla/gtfs2json/gtfs2json_gtfs.py", line 47, in _parse_shapes
    point = (float(row['shape_pt_lat']), float(row['shape_pt_lon']))
ValueError: could not convert string to float: 

```

Here is the relevant dataset: 
[keolis_merged_shaped_20170207.zip](https://github.com/panur/kartalla/files/791161/keolis_merged_shaped_20170207.zip)

shapes.txt file seems normally formatted (except maybe a large number of decimals in coordinates?)

Thanks for your help.

**Comment by panur** [comment]
The first problem is that gtfs2json fails to decode this line in your shapes.txt:

`51,,,1,0.0`

The next problem is the naive detection of invalid shapes (7cf0786) that works only in Finland.

Unfortunately there're still more problems after these two.

**Comment by panur** [comment]
I analyzed this more closely and the biggest remaining problem is the same as in #16: services with many shapes.
